### PR TITLE
Added .gitignore file in the header-feature branch

### PR DESCRIPTION
**Pull request by micheaol**
Added .gitignore file in the header-feature branch

### CODE REVIEW

**Review by DanteAlonsoHT — CHANGES_REQUESTED** [review]
<h1> Status: Required Changes 🚫 </h1>

Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Improve the description in your Pull Request, explain what you did, what is the main scope, which files do you change or added, what you set up in your project in this pull request, and so on.
- [x] You should use the [Template provided by Microverse](https://github.com/microverseinc/readme-template) to your README file, remember you can remove unnecessary sections such as "Run tests" and "Deployment" sections due to you are not using those sections in your current proyect. Feel free to see [this EXAMPLE](https://github.com/DanteAlonsoHT/Leaderboard_API) to let you know what we expect from the students.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by micheaol** [comment]
Thank you for your feedback.
Please note that adjustments have been made as requested.

Thank you for your support.

**Review by BrianSammit — CHANGES_REQUESTED** [review]
# CHANGES REQUIRED :red_circle: 🛑 

Hi @micheaol, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] Please make sure you set up linter correctly. You did not set up linters for this branch; I can see that you set up linters for the branch `test-feature` but you send for review this branch `header-feature`. Please make sure you set up linter for the branch you are asking to merge. 
- [ ] Please also fix the merge conflict in this pull request before you send it for review. 
- [ ] It would be better if the pull request title is more descriptive. i.g: `"Hello Microverse" project`. Remember that the pull request must have a title that describes to the whole project. 
- [ ] As the previous reviewer ask for make the pull request more descriptive. i.g:
 ```
In this pull request I added: 
  - index.html
  - main.css
  - ....etc
 ```

- [ ] Please add the `.css` file in this branch, because this branch is the one you send for review. 

I see that you work on 2 branches this is given you problems with the Github flow you must follow. You send this branch for review so please make sure all the project requirements are in this branch before you send it for review.

----------
Please fix these minor errors and send it again for another review :+1: :100: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 



**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by GzimAsani — COMMENTED** [review]
# Hello @micheaol 

## Unfortunately, I will have to invalidate this project because the pull request is already merged and I cannot do a proper re-review. You should not merge the pull request before getting approved

## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 You can also consider:
 
 Cheers and Happy coding!

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
